import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';import {parsePhase} from '../src/prepostDomain.mjs';
test('pre/post records enforce teacher ownership, immutable criteria, validated phases and optimistic corrections',async()=>{
 const db=new PGlite(),teacher='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222',pupil='33333333-3333-4333-8333-333333333333',student='44444444-4444-4444-8444-444444444444',foreign='55555555-5555-4555-8555-555555555555',id='66666666-6666-4666-8666-666666666666';
 const criteria=Array.from({length:5},()=>({max_score:10,method:'สิบข้อ ข้อละหนึ่งคะแนน'}));const pre=parsePhase({assessed_at:'2026-10-07T09:00',reading_text:'ชุด A',scores:['1','2','3','4','5'],help_level:'independent',note:''},criteria),post={...pre,assessed_at:'2026-10-08T09:00:00Z',scores:[2,3,4,5,6],comparable:true};
 try{await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated,anon;insert into auth.users values('${teacher}'),('${other}'),('${pupil}');`);
 const directory=new URL('../supabase/migrations/',import.meta.url);for(const file of (await fs.readdir(directory)).filter(f=>f.endsWith('.sql')).sort())await db.exec(await fs.readFile(new URL(file,directory),'utf8'));
 await db.query('insert into readtech_teachers(id,display_name) values($1,$2),($3,$4)',[teacher,'ครูหนึ่ง',other,'ครูสอง']);await db.query('insert into readtech_students(id,teacher_id,code,display_name,auth_user_id,login_id,login_enabled) values($1,$2,$3,$4,$5,$3,true),($6,$7,$8,$9,null,null,false)',[student,teacher,'0123','นักอ่าน',pupil,foreign,other,'0124','อีกคน']);
 const asUser=(uid,sql,params=[])=>db.transaction(async tx=>{await tx.exec('set local role authenticated');await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[uid]);return tx.query(sql,params);});
 const insert=(uid,studentId=student,value=criteria)=>asUser(uid,'insert into readtech_prepost_assessments(id,student_id,teacher_id,title,criteria) values($1,$2,$3,$4,$5::jsonb) returning *',[id,studentId,teacher,'A',JSON.stringify(value)]);
 await assert.rejects(insert(pupil),e=>e.code==='42501');await assert.rejects(insert(other),e=>e.code==='42501');await assert.rejects(insert(teacher,foreign),e=>e.code==='42501');await assert.rejects(insert(teacher,student,criteria.slice(0,4)),e=>e.code==='23514');
 const first=(await insert(teacher)).rows[0];assert.equal(first.pre,null);assert.equal(first.post,null);
 for(const uid of [other,pupil])assert.equal((await asUser(uid,'select * from readtech_prepost_assessments')).rows.length,0);
 const update=(uid,stage,value,revision)=>asUser(uid,`update readtech_prepost_assessments set ${stage}=$1::jsonb where id=$2 and revision=$3 returning *`,[JSON.stringify(value),id,revision]);
 await assert.rejects(update(teacher,'post',post,1),e=>e.code==='23514');await assert.rejects(update(teacher,'pre',{...pre,scores:[99,2,3,4,5]},1),e=>e.code==='23514');await assert.rejects(update(teacher,'pre',{...pre,correct_words:8,incorrect_words:2,skipped_words:3},1),e=>e.code==='23514');await assert.rejects(update(teacher,'pre',{...pre,reading_seconds:-1},1),e=>e.code==='23514');await assert.rejects(update(teacher,'pre',{...pre,help_level:'invalid'},1),e=>e.code==='23514');
 assert.equal((await update(teacher,'pre',pre,1)).rows[0].revision,2);await assert.rejects(update(teacher,'post',{...post,assessed_at:'2026-10-06T09:00:00Z'},2),e=>e.code==='23514');assert.equal((await update(teacher,'post',post,2)).rows[0].post.comparable,true);
 assert.equal((await update(pupil,'post',post,3)).rows.length,0);assert.equal((await update(other,'post',post,3)).rows.length,0);assert.equal((await update(teacher,'pre',pre,1)).rows.length,0);
 const correction=(await update(teacher,'pre',{...pre,scores:[0,2,3,4,5]},3)).rows[0];assert.equal(correction.revision,4);assert.equal(correction.post.comparable,false);
 for(const column of ['criteria','student_id','title','revision'])await assert.rejects(asUser(teacher,`update readtech_prepost_assessments set ${column}=${column} where id=$1`,[id]),e=>e.code==='42501');
 await assert.rejects(asUser(teacher,'delete from readtech_prepost_assessments where id=$1',[id]),e=>e.code==='42501');await db.query('update readtech_teachers set active=false where id=$1',[teacher]);assert.equal((await asUser(teacher,'select * from readtech_prepost_assessments')).rows.length,0);
 await assert.rejects(db.transaction(async tx=>{await tx.exec('set local role anon');return tx.query('select * from readtech_prepost_assessments');}),e=>e.code==='42501');
 }finally{await db.close();}
});
