import {useEffect,useRef,useState} from 'react';
import type {FormEvent} from 'react';
import type {SupabaseClient} from '@supabase/supabase-js';
import type {Student} from '../cloud';
import {fetchPrePost,createPrePost,savePhase} from '../prepostAssessments';
import type {PrePost,Phase} from '../prepostAssessments';
import {ASSESSMENT_DOMAINS,parseCriteria,parsePhase,phasePercentage,assessmentCsv} from '../prepostDomain.mjs';
import {READING_HELP,readingAccuracy} from '../readingDomain.mjs';
import {Icon} from './Icon';
function dateInput(value?:string){const d=value?new Date(value):new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}T${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;}
function freshPhase(phase?:Phase|null){return {assessed_at:dateInput(phase?.assessed_at),reading_text:phase?.reading_text??'',scores:phase?.scores.map(String)??Array(5).fill('') as string[],help_level:phase?.help_level??'',correct_words:phase?.correct_words==null?'':String(phase.correct_words),incorrect_words:phase?.incorrect_words==null?'':String(phase.incorrect_words),letter_swaps:phase?.letter_swaps==null?'':String(phase.letter_swaps),skipped_words:phase?.skipped_words==null?'':String(phase.skipped_words),stops:phase?.stops==null?'':String(phase.stops),reading_seconds:phase?.reading_seconds==null?'':String(phase.reading_seconds),note:phase?.note??'',comparable:phase?.comparable??false};}
const labels={pre:'ก่อนฝึก (Pre-test)',post:'หลังฝึก (Post-test)'};
export function PrePostPanel({client,student,teacherId}:{client:SupabaseClient;student:Student;teacherId:string}){
 const [rows,setRows]=useState<PrePost[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(''),[refresh,setRefresh]=useState(0);
 const [selected,setSelected]=useState(''),[createOpen,setCreateOpen]=useState(false),[stage,setStage]=useState<'pre'|'post'|null>(null),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [criteriaDraft,setCriteriaDraft]=useState({title:'',criteria:ASSESSMENT_DOMAINS.map(()=>({max_score:'',method:''}))});
 const [draft,setDraft]=useState(freshPhase);const requestId=useRef(''),busy=useRef(false),alive=useRef(true),form=useRef<HTMLFormElement>(null);
 const row=rows.find(r=>r.id===selected)??rows[0];
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>{let active=true;setLoading(true);setLoadError('');void fetchPrePost(client,student.id).then(data=>{if(active)setRows(data);}).catch(e=>{if(active)setLoadError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[client,student.id,refresh]);
 useEffect(()=>{if(stage||createOpen){form.current?.scrollIntoView({block:'nearest'});form.current?.querySelector<HTMLInputElement>('input')?.focus({preventScroll:true});}},[stage,createOpen]);
 function put(saved:PrePost){setRows(previous=>[saved,...previous.filter(r=>r.id!==saved.id)]);setSelected(saved.id);}
 function close(){setCreateOpen(false);setStage(null);setError('');}
 async function create(event:FormEvent){event.preventDefault();if(busy.current)return;let value;try{value=parseCriteria(criteriaDraft);}catch(e){setError((e as Error).message);return;}busy.current=true;setSaving(true);setError('');try{const saved=await createPrePost(client,student.id,teacherId,requestId.current,value);if(alive.current){put(saved);close();setMessage('สร้างชุดประเมินแล้ว เริ่มบันทึกผลก่อนฝึกได้');}}catch(e){if(alive.current)setError((e as Error).message);}finally{busy.current=false;if(alive.current)setSaving(false);}}
 async function save(event:FormEvent){event.preventDefault();if(busy.current||!row||!stage)return;let value:Phase;try{value=parsePhase(draft,row.criteria) as Phase;if(stage==='post'&&(!row.pre||Date.parse(value.assessed_at)<Date.parse(row.pre.assessed_at)))throw new Error('วันประเมินหลังฝึกต้องไม่อยู่ก่อนวันประเมินก่อนฝึก');if(stage==='pre'&&row.post&&Date.parse(value.assessed_at)>Date.parse(row.post.assessed_at))throw new Error('วันประเมินก่อนฝึกต้องไม่อยู่หลังวันประเมินหลังฝึก');}catch(e){setError((e as Error).message);return;}busy.current=true;setSaving(true);setError('');try{const saved=await savePhase(client,row,stage,value);if(alive.current){put(saved);close();setMessage('บันทึกผลประเมินแล้ว');}}catch(e){if(alive.current)setError((e as Error).message);}finally{busy.current=false;if(alive.current)setSaving(false);}}
 function openPhase(next:'pre'|'post'){setCreateOpen(false);setStage(next);setDraft(freshPhase(row?.[next]));setError('');setMessage('');}
 function exportCsv(){if(!row)return;const url=URL.createObjectURL(new Blob([assessmentCsv(row,student)],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`prepost-${student.code}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const field=(key:keyof typeof draft,value:string|boolean)=>setDraft(old=>({...old,[key]:value}));
 const locked=loading||saving||Boolean(loadError)||Boolean(stage)||createOpen;
 return <section className="reading-panel prepost-panel" aria-label={`ประเมินก่อน–หลังของ ${student.display_name}`}>
 <div className="reading-panel-heading"><div><h2>ประเมินก่อน–หลัง 5 ด้าน</h2><p>ครูบันทึกผลจากแบบประเมินที่เตรียมเอง</p></div><button className="primary" disabled={locked} onClick={()=>{setCreateOpen(true);setCriteriaDraft({title:'',criteria:ASSESSMENT_DOMAINS.map(()=>({max_score:'',method:''}))});requestId.current=crypto.randomUUID();setError('');setMessage('');}}>สร้างชุดประเมิน<Icon name="book" size={18}/></button></div>
 <p className="reading-guidance">กำหนดคะแนนเต็มและวิธีให้คะแนนเองครบทั้ง 5 ด้าน ใช้เกณฑ์เดียวกันก่อน–หลัง คะแนนนี้แยกจากเกม และยังไม่มีข้อสอบอัตโนมัติ</p>
 {loading&&<p role="status">กำลังโหลดชุดประเมิน…</p>}{loadError&&<div><p className="reading-error" role="alert">{loadError}</p><button className="secondary" onClick={()=>setRefresh(n=>n+1)}>ลองโหลดชุดประเมินอีกครั้ง</button></div>}{message&&<p className="reading-saved" role="status">{message}</p>}
 {createOpen&&<form ref={form} className="reading-form" aria-label="สร้างชุดประเมิน" onSubmit={e=>void create(e)}><fieldset disabled={saving}><legend>เกณฑ์ของชุดประเมินนี้</legend><label className="prepost-label">ชื่อชุดประเมิน<input required maxLength={200} value={criteriaDraft.title} onChange={e=>setCriteriaDraft(old=>({...old,title:e.target.value}))}/></label><p className="reading-field-help">เกณฑ์จะคงเดิมหลังสร้างชุด หากต้องเปลี่ยนเกณฑ์ให้สร้างชุดใหม่ เพื่อให้ผลก่อน–หลังใช้คะแนนเต็มและวิธีประเมินเดียวกัน</p>
 {ASSESSMENT_DOMAINS.map((name,i)=><div className="prepost-criterion" key={name}><h3>ด้านที่ {i+1} {name}</h3><div className="reading-fields"><label>คะแนนเต็มด้านที่ {i+1}<input required type="number" min="0.01" max="10000" step="0.01" value={criteriaDraft.criteria[i].max_score} onChange={e=>setCriteriaDraft(old=>({...old,criteria:old.criteria.map((c,j)=>j===i?{...c,max_score:e.target.value}:c)}))}/></label><label>วิธีประเมินด้านที่ {i+1}<textarea required maxLength={500} rows={2} value={criteriaDraft.criteria[i].method} onChange={e=>setCriteriaDraft(old=>({...old,criteria:old.criteria.map((c,j)=>j===i?{...c,method:e.target.value}:c)}))} placeholder="ระบุกิจกรรม จำนวนข้อ และวิธีให้คะแนน"/></label></div></div>)}
 {error&&<p role="alert" className="reading-error">{error}</p>}<div className="reading-form-actions"><button className="primary" type="submit">{saving?'กำลังสร้าง…':'บันทึกเกณฑ์และสร้างชุด'}</button><button className="secondary" type="button" onClick={close}>ยกเลิก</button></div></fieldset></form>}
 {!loading&&!loadError&&!rows.length&&!createOpen&&<p className="reading-empty">ยังไม่มีชุดประเมิน เริ่มจากกำหนดเกณฑ์ทั้ง 5 ด้าน</p>}
 {row&&<><label className="prepost-label">ชุดประเมินที่ต้องการดู<select aria-label="ชุดประเมินที่ต้องการดู" disabled={locked} value={row.id} onChange={e=>{setSelected(e.target.value);setMessage('');}}>{rows.map(r=><option key={r.id} value={r.id}>{r.title} · {r.post?'มีผลก่อน–หลัง':r.pre?'มีผลก่อนฝึก':'รอบันทึก'} · {new Date(r.created_at).toLocaleDateString('th-TH')}</option>)}</select></label><div className="reading-form-actions prepost-actions"><button className="secondary" disabled={locked} onClick={()=>openPhase('pre')}>{row.pre?'แก้ไขผลก่อนฝึก':'บันทึกผลก่อนฝึก'}</button><button className="secondary" disabled={locked||!row.pre} onClick={()=>openPhase('post')}>{row.post?'แก้ไขผลหลังฝึก':'บันทึกผลหลังฝึก'}</button><button className="text-button" disabled={loading||saving||Boolean(loadError)||(!row.pre&&!row.post)} onClick={exportCsv}>ส่งออกก่อน–หลัง CSV<Icon name="download" size={16}/></button></div>
 {stage&&<form ref={form} className="reading-form" aria-label={labels[stage]} onSubmit={e=>void save(e)}><h3>{labels[stage]}</h3><fieldset disabled={saving}><legend className="sr-only">ผลประเมินทั้ง 5 ด้าน</legend><div className="reading-fields"><label>วันเวลาประเมิน<input required type="datetime-local" value={draft.assessed_at} onChange={e=>field('assessed_at',e.target.value)}/></label><label>ชุดคำหรือแบบประเมินที่ใช้<input required maxLength={500} value={draft.reading_text} onChange={e=>field('reading_text',e.target.value)}/></label></div>
 {row.criteria.map((c,i)=><div key={i} className="prepost-criterion"><label className="prepost-label">คะแนนด้านที่ {i+1}: {ASSESSMENT_DOMAINS[i]} (เต็ม {c.max_score})<input aria-label={`คะแนนด้านที่ ${i+1}`} required type="number" min={0} max={c.max_score} step="0.01" value={draft.scores[i]} onChange={e=>setDraft(old=>({...old,scores:old.scores.map((s,j)=>j===i?e.target.value:s)}))}/></label><p className="reading-field-help">วิธีประเมิน: {c.method}</p></div>)}
 <h4>บันทึกการอ่านเพิ่มเติม (เว้นว่างเมื่อไม่ได้บันทึก)</h4><p className="reading-field-help">อ่านผิดให้นับรวมคำที่อ่านไม่ได้หรือข้าม เป้าหมายอ่านถูก 80% คำนวณเฉพาะจำนวนคำจริง ไม่ใช่คะแนน 5 ด้าน</p><div className="reading-fields">{([{key:'correct_words',label:'จำนวนคำอ่านถูก'},{key:'incorrect_words',label:'จำนวนคำอ่านผิด'},{key:'letter_swaps',label:'สลับตัวอักษร (ครั้ง)'},{key:'skipped_words',label:'อ่านข้าม (คำ)'},{key:'stops',label:'หยุดกลางคัน (ครั้ง)'},{key:'reading_seconds',label:'เวลาอ่าน (วินาที)'}] as const).map(f=><label key={f.key}>{f.label}<input type="number" min={f.key==='reading_seconds'?1:0} max={f.key==='reading_seconds'?86400:10000} step={1} value={draft[f.key]} onChange={e=>field(f.key,e.target.value)}/></label>)}<label className="reading-wide">ความช่วยเหลือในการประเมิน<select aria-label="ความช่วยเหลือในการประเมิน" required value={draft.help_level} onChange={e=>field('help_level',e.target.value)}><option value="">เลือกระดับความช่วยเหลือ</option>{Object.entries(READING_HELP).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="reading-wide">หมายเหตุการประเมิน<textarea maxLength={500} rows={2} value={draft.note} onChange={e=>field('note',e.target.value)}/></label></div>
 {stage==='post'&&<label className="prepost-confirm"><input type="checkbox" checked={draft.comparable} onChange={e=>field('comparable',e.target.checked)}/><span>ครูยืนยันว่าชุดคำและเงื่อนไขก่อน–หลังเทียบกันได้ เพื่อแสดงผลต่างคะแนน</span></label>}
 {error&&<p className="reading-error" role="alert">{error}</p>}<div className="reading-form-actions"><button className="primary" type="submit">{saving?'กำลังบันทึก…':'บันทึกผลประเมิน'}</button><button className="secondary" type="button" onClick={close}>ยกเลิก</button><button className="text-button" type="button" onClick={()=>{close();setRefresh(n=>n+1);}}>โหลดชุดประเมินล่าสุด</button></div></fieldset></form>}
 <h3>เปรียบเทียบทั้ง 5 ด้าน</h3>{!row.post?.comparable&&<p className="reading-field-help">ผลต่างจะแสดงเมื่อมีผลครบก่อน–หลังและครูยืนยันว่าเทียบกันได้</p>}{row.pre&&row.post&&(row.pre.reading_text!==row.post.reading_text||row.pre.help_level!==row.post.help_level)&&<p className="reading-guidance">ชุดคำหรือความช่วยเหลือต่างกัน ควรพิจารณาบริบทประกอบผลต่างคะแนน</p>}
 <p className="prepost-scroll-hint reading-field-help">เลื่อนตารางซ้าย–ขวาเพื่อดูคะแนนก่อน–หลังและผลต่าง</p><div className="prepost-table-wrap" role="region" aria-label="ตารางเปรียบเทียบ 5 ด้าน เลื่อนแนวนอนได้" tabIndex={0}><table className="prepost-table"><caption>{row.title} · คะแนนและร้อยละตามเกณฑ์ครู</caption><thead><tr><th scope="col">ด้าน</th><th scope="col">ก่อนฝึก</th><th scope="col">หลังฝึก</th><th scope="col">ผลต่าง</th></tr></thead><tbody>{ASSESSMENT_DOMAINS.map((name,i)=><tr key={name}><th scope="row">{i+1}. {name}<small>เต็ม {row.criteria[i].max_score}</small></th>{(['pre','post'] as const).map(s=><td key={s}>{row[s]?<>{row[s]!.scores[i]}<small>{phasePercentage(row[s],row.criteria,i)!.toFixed(2)}%</small></>:'ยังไม่บันทึก'}</td>)}<td>{row.pre&&row.post?.comparable?<>{(phasePercentage(row.post,row.criteria,i)!-phasePercentage(row.pre,row.criteria,i)!).toLocaleString('th-TH',{maximumFractionDigits:2,signDisplay:'exceptZero'})}<small>จุดเปอร์เซ็นต์</small></>:'—'}</td></tr>)}</tbody></table></div>
 <div className="prepost-context">{(['pre','post'] as const).map(s=>{const p=row[s];if(!p)return <article key={s}><h4>{labels[s]}</h4><p>ยังไม่บันทึก</p></article>;const accuracy=p.correct_words===null?null:readingAccuracy(p.correct_words,p.incorrect_words!);return <article key={s}><h4>{labels[s]}</h4><p><time dateTime={p.assessed_at}>{new Date(p.assessed_at).toLocaleString('th-TH')}</time></p><p>ชุดคำ: {p.reading_text}</p><p>ความช่วยเหลือ: {READING_HELP[p.help_level]}</p><dl>{[['อ่านถูก / อ่านผิด',p.correct_words===null?'ยังไม่ได้บันทึก':`${p.correct_words} / ${p.incorrect_words} คำ`],['อ่านถูกจริง',accuracy?`${accuracy.percentage.toFixed(2)}% · ${accuracy.reached?'ถึง':'ยังไม่ถึง'}เป้าหมาย 80%`:'ยังไม่ได้บันทึก'],['สลับตัวอักษร',p.letter_swaps===null?'ยังไม่ได้บันทึก':`${p.letter_swaps} ครั้ง`],['อ่านข้าม',p.skipped_words===null?'ยังไม่ได้บันทึก':`${p.skipped_words} คำ`],['หยุดกลางคัน',p.stops===null?'ยังไม่ได้บันทึก':`${p.stops} ครั้ง`],['เวลาอ่าน',p.reading_seconds===null?'ไม่ได้จับเวลา':`${p.reading_seconds} วินาที`]].map(([name,value])=><div key={name}><dt>{name}</dt><dd>{value}</dd></div>)}</dl>{p.note&&<p>หมายเหตุ: {p.note}</p>}</article>;})}</div><p className="fine-print">ผลต่างเป็นการเปรียบเทียบบันทึกของครู ยังไม่ใช่ผลรับรองประสิทธิผลของโปรแกรม</p>
 </>}
 </section>;
}
